//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoRCheats.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoRCheats.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			UnlockableCatalog.RegisterUnlockable(&quot;Logs.BeetleBody.0&quot;, new UnlockableDef
        ///			{
        ///				nameToken = &quot;UNLOCKABLE_LOG_BEETLE&quot;
        ///			});
        ///			UnlockableCatalog.RegisterUnlockable(&quot;Logs.BeetleGuardBody.0&quot;, new UnlockableDef
        ///			{
        ///				nameToken = &quot;UNLOCKABLE_LOG_BEETLEGUARD&quot;
        ///			});
        ///			UnlockableCatalog.RegisterUnlockable(&quot;Logs.BeetleQueenBody.0&quot;, new UnlockableDef
        ///			{
        ///				nameToken = &quot;UNLOCKABLE_LOG_BEETLEQUEEN&quot;
        ///			});
        ///			UnlockableCatalog.RegisterUnlockable(&quot;Logs.BisonBody.0&quot;, new UnlockableDef
        ///			{
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Unlockables {
            get {
                return ResourceManager.GetString("Unlockables", resourceCulture);
            }
        }
    }
}
